//! Basic VM Exit Reasons

use core::convert::From;

#[derive(Debug)]
#[allow(dead_code)]
#[allow(non_camel_case_types)]
pub enum ExitReason {
    EXCEPTION_OR_NMI,
    EXTERNAL_INTERRUPT,
    TRIPLE_FAULT,
    INIT_SIGNAL,
    STARTUP_IPI,
    IO_SMI,
    OTHER_SMI,
    INTERRUPT_WINDOW,
    NMI_WINDOW,
    TASK_SWITCH,
    CPUID,
    GETSEC,
    HLT,
    INVD,
    INVLPG,
    RDPMC,
    RDTSC,
    RSM,
    VMCALL,
    VMCLEAR,
    VMLAUNCH,
    VMPTRLD,
    VMPTRST,
    VMREAD,
    VMRESUME,
    VMWRITE,
    VMXOFF,
    VMXON,
    CONTROL_REGISTER_ACCESS,
    MOV_DR,
    IO_INSTRUCTION,
    RDMSR,
    WRMSR,
    ENTRY_FAILURE_GUEST_STATE,
    ENTRY_FAILURE_MSR_LOADING,
    MWAIT,
    MONITOR_TRAP_FLAG,
    MONITOR,
    PAUSE,
    ENTRY_FAILURE_MACHINE_CHECK,
    TPR_BELOW_THRESHOLD,
    APIC_ACCESS,
    VIRTUALIZED_EOI,
    ACCESS_GDTR_OR_IDTR,
    ACCESS_LDTR_OR_TR,
    EPT_VIOLATION,
    EPT_MISCONFIGURATION,
    INVEPT,
    RDTSCP,
    VMX_PREEMPT_TIMER_EXPIRED,
    INVVPID,
    WBINVD,
    XSETBV,
    APIC_WRITE,
    RDRAND,
    INVPCID,
    VMFUNC,
    ENCLS,
    RDSEED,
    PAGE_MODIFICATION_LOG_FULL,
    XSAVES,
    XRSTORS,
    SPP_EVENT,
    UMWAIT,
    TPAUSE,
    UNKNOWN(u32),
}

impl From<u32> for ExitReason {
    fn from(code: u32) -> Self {
        use ExitReason::*;
        match code {
            0 => EXCEPTION_OR_NMI,
            1 => EXTERNAL_INTERRUPT,
            2 => TRIPLE_FAULT,
            3 => INIT_SIGNAL,
            4 => STARTUP_IPI,
            5 => IO_SMI,
            6 => OTHER_SMI,
            7 => INTERRUPT_WINDOW,
            8 => NMI_WINDOW,
            9 => TASK_SWITCH,
            10 => CPUID,
            11 => GETSEC,
            12 => HLT,
            13 => INVD,
            14 => INVLPG,
            15 => RDPMC,
            16 => RDTSC,
            17 => RSM,
            18 => VMCALL,
            19 => VMCLEAR,
            20 => VMLAUNCH,
            21 => VMPTRLD,
            22 => VMPTRST,
            23 => VMREAD,
            24 => VMRESUME,
            25 => VMWRITE,
            26 => VMXOFF,
            27 => VMXON,
            28 => CONTROL_REGISTER_ACCESS,
            29 => MOV_DR,
            30 => IO_INSTRUCTION,
            31 => RDMSR,
            32 => WRMSR,
            33 => ENTRY_FAILURE_GUEST_STATE,
            34 => ENTRY_FAILURE_MSR_LOADING,
            36 => MWAIT,
            37 => MONITOR_TRAP_FLAG,
            39 => MONITOR,
            40 => PAUSE,
            41 => ENTRY_FAILURE_MACHINE_CHECK,
            43 => TPR_BELOW_THRESHOLD,
            44 => APIC_ACCESS,
            45 => VIRTUALIZED_EOI,
            46 => ACCESS_GDTR_OR_IDTR,
            47 => ACCESS_LDTR_OR_TR,
            48 => EPT_VIOLATION,
            49 => EPT_MISCONFIGURATION,
            50 => INVEPT,
            51 => RDTSCP,
            52 => VMX_PREEMPT_TIMER_EXPIRED,
            53 => INVVPID,
            54 => WBINVD,
            55 => XSETBV,
            56 => APIC_WRITE,
            57 => RDRAND,
            58 => INVPCID,
            59 => VMFUNC,
            60 => ENCLS,
            61 => RDSEED,
            62 => PAGE_MODIFICATION_LOG_FULL,
            63 => XSAVES,
            64 => XRSTORS,
            66 => SPP_EVENT,
            67 => UMWAIT,
            68 => TPAUSE,
            c => UNKNOWN(c),
        }
    }
}
