name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2020-06-04
        override: true
        components: rustfmt, clippy
    - name: Check code format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2020-06-04
        components: rust-src
        target: riscv64imac-unknown-none-elf
    - name: Build x86_64
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-features
    - name: Build RISC-V 64
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --target riscv64imac-unknown-none-elf --all-features
    - name: Build example UEFI
      run: cd examples/uefi && make build
    - name: Build example KO
      run: |
        cd examples/ko && make
    - name: Build docs
      uses: actions-rs/cargo@v1
      with:
        command: doc

  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2020-06-04
        components: rust-src
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
